spring:
  jpa:
    database: postgresql
    hibernate.ddl-auto: none
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      format_sql: true
  sql.init.mode: always
  config:
    activate:
      on-profile: ci,test
  main.allow-bean-definition-overriding: true
  datasource:
    driverClassName: org.h2.Driver
    url: "jdbc:h2:mem:shareit;MODE=PostgreSQL"
    username: test
    password: test

    secondary:
      url: "jdbc:postgresql://localhost:5432/shareit"
      driver-class-name: org.postgresql.Driver
      username: TestUser
      password: 1111

hibernate.show_sql: true

logging.level:
  org.springframework:
    orm.jpa: INFO
    orm.jpa.JpaTransactionManager: DEBUG
    transaction: INFO
    transaction.interceptor: TRACE
  org.hibernate:
    SQL: DEBUG
    type.descriptor.sql.BasicBinder: TRACE