create table if not exists users (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR (100) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
CONSTRAINT check_email CHECK (email ~'^[A-Za-z0-9._%-]+@[A-Za-z0-9.-]+[.][A-Za-z]+$')
)

create table if not exists requests (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
description VARCHAR NOT NULL,
requestor_id INTEGER REFERENCES users (id) ON DELETE CASCADE NOT NULL,
created DATE
)

create table if not exists items (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR (100) NOT NULL,
description VARCHAR,
is_available BOOLEAN DEFAULT TRUE,
owner_id INTEGER REFERENCES users (id) ON DELETE CASCADE NOT NULL,
request_id INTEGER REFERENCES requests (id) ON DELETE CASCADE
)

create table if not exists booking (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
start_date DATE NOT NULL,
end_date DATE NOT NULL,
item_id INTEGER REFERENCES items (id) ON DELETE CASCADE NOT NULL,
booker_id INTEGER REFERENCES users (id) ON DELETE CASCADE NOT NULL,
status VARCHAR(10) DEFAULT 'WAITING'
)