server.port: 2000
spring:
  jpa:
    hibernate.ddl-auto: none
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      format_sql: true
  sql.init.mode: always
  main.allow-bean-definition-overriding: true
  datasource:
    url: "jdbc:postgresql://localhost:6555/shareit"
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DB_USER} #TestUser
    password: ${SPRING_DB_PASSWORD} #1111
hibernate.show_sql: true
logging.level:
  org.springframework:
    orm.jpa: INFO
    orm.jpa.JpaTransactionManager: DEBUG
    transaction: INFO
    transaction.interceptor: TRACE
  org.hibernate:
    SQL: DEBUG
    type.descriptor.sql.BasicBinder: TRACE
